import { COUNTRIES, DEFAULT_COUNTRY, type Country } from '@/data/countries';
import type { IdentifierConfig, Member } from '@/domain/types';
import { internationalPhone, validatePerson } from '@/domain/userValidation';
import { newId } from '@/lib/identifiers';
import type { PersonForm } from '@/pages/users/add/draft';
import { IdSwitchUnavailableError, type IdSwitchService, type ResolutionResult } from '@/services/types';
import type { CreateUserInput } from '@/store/operations';

/** Most users one file can add. Larger lists can be split across files. */
export const MAX_IMPORT_ROWS = 1000;
export const MAX_IMPORT_BYTES = 1024 * 1024;

type PersonKey = 'givenName' | 'familyName' | 'email' | 'phone' | 'country' | 'region' | 'gender';

/** The user information the individual Create User form collects, in the same order and with the same labels. */
export const PERSON_COLUMNS: { key: PersonKey; header: string; required: boolean }[] = [
  { key: 'givenName', header: 'First Name', required: true },
  { key: 'familyName', header: 'Last Name', required: true },
  { key: 'email', header: 'Email Address', required: true },
  { key: 'phone', header: 'Phone Number', required: false },
  { key: 'country', header: 'Country', required: false },
  { key: 'region', header: 'Region/State', required: false },
  { key: 'gender', header: 'Gender', required: false },
];

/** Columns added to downloaded reports; ignored when a corrected report is uploaded again. */
export const REPORT_ROW = 'Row';
export const REPORT_ERRORS = 'Errors';

/** Template headings for an identifier: manual identifiers are a required first column; generated ones aren't in the file. */
export function templateHeaders(config: IdentifierConfig): string[] {
  return [...(config.mode === 'manual' ? [config.name] : []), ...PERSON_COLUMNS.map((c) => c.header)];
}

export const templateFileName = (config: IdentifierConfig) => `fixid-user-import-${config.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}.csv`;

const norm = (v: string) => v.trim().toLowerCase().replace(/\s+/g, ' ');

export type HeaderCheck = { ok: true; index: Map<string, number> } | { ok: false; errors: string[] };

/** Checks the file's column headings against the template for the selected identifier. */
export function checkHeader(header: string[], config: IdentifierConfig, otherConfigs: IdentifierConfig[]): HeaderCheck {
  const cells = header.map((h) => h.trim());
  if (cells.every((h) => !h)) return { ok: false, errors: ['The first row must contain the column headings from the template.'] };
  const errors: string[] = [];
  const index = new Map<string, number>();
  const known = new Map<string, string>(PERSON_COLUMNS.map((c) => [norm(c.header), c.key]));
  if (config.mode === 'manual') known.set(norm(config.name), 'identifier');
  const others = new Map(otherConfigs.filter((c) => c.id !== config.id).map((c) => [norm(c.name), c]));
  const seen = new Set<string>();

  cells.forEach((h, i) => {
    const n = norm(h);
    if (!n) { errors.push(`Column ${i + 1} has no heading.`); return; }
    if (seen.has(n)) { errors.push(`The column “${h}” appears more than once.`); return; }
    seen.add(n);
    if (n === norm(REPORT_ROW) || n === norm(REPORT_ERRORS)) return;
    if (config.mode === 'generated' && n === norm(config.name)) {
      errors.push(`${config.name} is generated by FixID, so the file can’t include a “${h}” column. Download the template for ${config.name} and use that.`);
      return;
    }
    const other = others.get(n);
    if (other) {
      errors.push(`This file has a “${h}” column, but you selected ${config.name}. Download the template for ${config.name}, or select ${other.name} instead.`);
      return;
    }
    const key = known.get(n);
    if (!key) { errors.push(`“${h}” isn’t a column in the template.`); return; }
    index.set(key, i);
  });
  const required = [...(config.mode === 'manual' ? [{ key: 'identifier', header: config.name }] : []), ...PERSON_COLUMNS.filter((c) => c.required)];
  const missing = required.filter((c) => !index.has(c.key)).map((c) => c.header);
  if (missing.length) errors.push(`Missing ${missing.length === 1 ? 'column' : 'columns'}: ${missing.join(', ')}.`);
  return errors.length ? { ok: false, errors } : { ok: true, index };
}

export type RecordStatus = 'valid' | 'invalid';

export interface ImportRecord {
  /** Row number in the spreadsheet (the heading row is row 1). */
  row: number;
  /** Values as they appear in the file, keyed by template heading, for reports. */
  values: Record<string, string>;
  person: PersonForm;
  status: RecordStatus;
  errors: string[];
  /** Identity check result; set for records that passed the field checks. */
  resolution?: ResolutionResult;
  note?: string;
}

function findCountry(v: string): Country | undefined | null {
  const n = norm(v);
  if (!n) return undefined;
  return COUNTRIES.find((c) => c.code.toLowerCase() === n || norm(c.name) === n) ?? null;
}

/** The calling-code country for a phone number: from its + prefix, else the row's country, else the default. */
function phoneCountryFor(phone: string, country?: Country): string {
  const t = phone.trim();
  const digits = t.replace(/\D/g, '');
  const byPrefix = (d: string) => [...COUNTRIES].sort((a, b) => b.dial.length - a.dial.length).find((c) => d.startsWith(c.dial.slice(1)));
  if (t.startsWith('+')) return byPrefix(digits)?.code ?? country?.code ?? DEFAULT_COUNTRY;
  return country?.code ?? DEFAULT_COUNTRY;
}

/**
 * Spreadsheets often drop the leading + from international numbers (2348035550101). Restore it when
 * the digits start with the expected calling code and are too long to be a national number.
 */
function restorePlus(phone: string, dial: string): string {
  const t = phone.trim();
  const cc = dial.slice(1);
  return /^\d+$/.test(t) && t.startsWith(cc) && t.length >= cc.length + 9 ? `+${t}` : t;
}

const LABEL: Record<keyof PersonForm, string> = {
  givenName: 'First Name', familyName: 'Last Name', email: 'Email Address', phone: 'Phone Number', phoneCountry: 'Phone Number',
  country: 'Country', region: 'Region/State', gender: 'Gender', identifierValue: '',
};

/**
 * Reads and validates the data rows with the same rules as the individual Create User flow, plus
 * duplicates within the file. Nothing is created or changed.
 */
export function readRecords(rows: string[][], index: Map<string, number>, headerCount: number, config: IdentifierConfig, taken: (v: string) => boolean): ImportRecord[] {
  const records: ImportRecord[] = [];
  const firstBy = { id: new Map<string, number>(), email: new Map<string, number>(), phone: new Map<string, number>() };
  rows.forEach((cells, i) => {
    const row = i + 2;
    if (cells.every((c) => !c.trim())) return;
    const get = (key: string) => (index.has(key) ? (cells[index.get(key)!] ?? '').trim() : '');
    const errors: string[] = [];
    if (cells.length > headerCount && cells.slice(headerCount).some((c) => c.trim())) errors.push(`This row has more values than there are columns (${cells.length} instead of ${headerCount}). Check for an unquoted comma.`);

    const countryRaw = get('country');
    const country = findCountry(countryRaw);
    if (country === null) errors.push(`Country: “${countryRaw}” isn’t a recognised country. Use the country name or its two-letter code.`);
    const phoneCountry = phoneCountryFor(get('phone'), country ?? undefined);
    const phone = restorePlus(get('phone'), COUNTRIES.find((c) => c.code === phoneCountry)!.dial);
    const genderRaw = norm(get('gender'));
    const gender = genderRaw === 'female' ? 'Female' : genderRaw === 'male' ? 'Male' : '';
    if (genderRaw && !gender) errors.push('Gender: use Female or Male, or leave it empty.');
    let region = get('region');
    if (region && country?.regions) {
      const match = country.regions.find((r) => norm(r) === norm(region));
      if (!match) errors.push(`Region/State: “${region}” isn’t a region of ${country.name}.`);
      else region = match;
    }
    const person: PersonForm = {
      givenName: get('givenName'), familyName: get('familyName'), email: get('email'), phone, phoneCountry,
      country: country?.code ?? '', region, gender, identifierValue: config.mode === 'manual' ? get('identifier') : '',
    };
    const fieldErrors = validatePerson(person, config, taken);
    for (const [k, msg] of Object.entries(fieldErrors)) errors.push(k === 'identifierValue' ? `${config.name}: ${msg}` : `${LABEL[k as keyof PersonForm]}: ${msg}`);

    const dup = (kind: keyof typeof firstBy, key: string, label: string) => {
      if (!key) return;
      const first = firstBy[kind].get(key);
      if (first) errors.push(`${label} is the same as row ${first}. Each user needs their own.`);
      else firstBy[kind].set(key, row);
    };
    if (config.mode === 'manual' && !fieldErrors.identifierValue) dup('id', person.identifierValue.toLowerCase(), config.name);
    if (!fieldErrors.email) dup('email', person.email.toLowerCase(), 'Email Address');
    if (!fieldErrors.phone) dup('phone', internationalPhone(person) ?? '', 'Phone Number');

    const values: Record<string, string> = {};
    if (config.mode === 'manual') values[config.name] = get('identifier');
    for (const c of PERSON_COLUMNS) values[c.header] = get(c.key);
    records.push({ row, values, person, status: errors.length ? 'invalid' : 'valid', errors });
  });
  return records;
}

/** Runs `fn` over items with limited concurrency, keeping result order. */
async function pool<T, R>(items: T[], limit: number, fn: (item: T) => Promise<R>): Promise<R[]> {
  const out: R[] = new Array(items.length);
  let next = 0;
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (next < items.length) { const i = next++; out[i] = await fn(items[i]); }
  }));
  return out;
}

/**
 * Checks valid records against existing identity records, as the individual flow does before creating a
 * user. Read-only. Throws IdSwitchUnavailableError when the identity service can't be reached.
 */
export async function checkIdentities(records: ImportRecord[], idSwitch: IdSwitchService, orgMembers: Member[]): Promise<ImportRecord[]> {
  const checked = await pool(records, 5, async (r) => {
    if (r.status === 'invalid') return r;
    const resolution = await idSwitch.resolveIdentity({ givenName: r.person.givenName, familyName: r.person.familyName, email: r.person.email, phone: internationalPhone(r.person) ?? '' });
    const invalid = (msg: string): ImportRecord => ({ ...r, resolution, status: 'invalid', errors: [msg] });
    if (resolution.kind === 'conflict') return invalid('The email address or phone number already belongs to a person with a different name.');
    if (resolution.kind === 'possible') return invalid('Someone with the same name is already on record. Add this person individually so you can confirm they’re a different person.');
    if (resolution.kind === 'match') {
      const existing = orgMembers.find((m) => m.idSwitchId === resolution.identity.idSwitchId);
      if (existing) return invalid(`${existing.displayName} is already a user in your organization. Existing users aren’t changed by an import.`);
      return { ...r, resolution, note: 'Will be linked to their existing record.' };
    }
    return { ...r, resolution };
  });
  return checked;
}

export type ResultStatus = 'created' | 'failed' | 'skipped' | 'not-processed';

export interface ImportResult {
  row: number;
  values: Record<string, string>;
  status: ResultStatus;
  memberId?: string;
  identifier?: string;
  reason?: string;
}

export interface ImportDeps {
  idSwitch: IdSwitchService;
  createUser: (input: CreateUserInput) => { ok: true; memberId: string; identifier: string } | { ok: false; errors: Record<string, string> };
  /** Members already created for a request ID (from an earlier, interrupted run of the same import). */
  createdFor: (requestId: string) => Member | undefined;
}

export const requestIdFor = (importId: string, row: number) => `${importId}-row-${row}`;

/**
 * Creates the valid records through the same createUser operation as the individual flow, one at a time.
 * Each row has a stable request ID, so running the same import again never creates a user twice.
 * If the identity service becomes unavailable, the remaining rows are left unprocessed.
 */
export async function runImport(
  deps: ImportDeps,
  job: { importId: string; organizationId: string; config: IdentifierConfig; records: ImportRecord[]; identities: Map<number, string> },
  onProgress?: (done: number) => void,
): Promise<ImportResult[]> {
  const results: ImportResult[] = [];
  let stopped: string | null = null;
  for (const r of job.records) {
    const base = { row: r.row, values: r.values };
    if (r.status === 'invalid') { results.push({ ...base, status: 'skipped', reason: r.errors.join(' ') }); continue; }
    if (stopped) { results.push({ ...base, status: 'not-processed', reason: stopped }); continue; }
    const requestId = requestIdFor(job.importId, r.row);
    const prior = deps.createdFor(requestId);
    if (prior) {
      results.push({ ...base, status: 'created', memberId: prior.id, identifier: prior.identifier?.value });
      onProgress?.(results.length);
      continue;
    }
    try {
      let identity: CreateUserInput['identity'];
      if (r.resolution?.kind === 'match') {
        identity = { idSwitchId: r.resolution.identity.idSwitchId, resolution: 'linked-existing' };
      } else {
        let id = job.identities.get(r.row);
        if (!id) {
          const p = r.person;
          const created = await deps.idSwitch.createIdentity({
            givenName: p.givenName, familyName: p.familyName, email: p.email, phone: internationalPhone(p) ?? '',
            gender: p.gender || undefined, country: COUNTRIES.find((c) => c.code === p.country)?.name, region: p.region || undefined,
          });
          id = created.idSwitchId;
          job.identities.set(r.row, id);
        }
        identity = { idSwitchId: id, resolution: 'created-new' };
      }
      const made = deps.createUser({
        requestId, organizationId: job.organizationId, at: new Date().toISOString(), identifierConfigId: job.config.id,
        identifierValue: r.person.identifierValue, person: { givenName: r.person.givenName, familyName: r.person.familyName },
        identity, memberId: newId('mem'),
      });
      results.push(made.ok
        ? { ...base, status: 'created', memberId: made.memberId, identifier: made.identifier }
        : { ...base, status: 'failed', reason: Object.values(made.errors)[0] ?? 'The user couldn’t be created.' });
    } catch (err) {
      if (err instanceof IdSwitchUnavailableError) {
        stopped = 'Not processed: the identity service became unavailable. Nothing was saved for this row; retry to continue.';
        results.push({ ...base, status: 'not-processed', reason: stopped });
      } else {
        results.push({ ...base, status: 'failed', reason: (err as Error).message || 'The user couldn’t be created.' });
      }
    }
    onProgress?.(results.length);
  }
  return results;
}

/** Rows for the downloadable results file, including identifiers FixID assigned. */
export function resultsCsv(config: IdentifierConfig, results: ImportResult[]): string[][] {
  const label: Record<ResultStatus, string> = { created: 'Created', failed: 'Failed', skipped: 'Skipped', 'not-processed': 'Not processed' };
  return [
    [REPORT_ROW, 'Status', config.name, 'First Name', 'Last Name', 'Email Address', 'Reason'],
    ...results.map((r) => [String(r.row), label[r.status], r.identifier ?? (config.mode === 'manual' ? r.values[config.name] ?? '' : ''),
      r.values['First Name'] ?? '', r.values['Last Name'] ?? '', r.values['Email Address'] ?? '', r.reason ?? '']),
  ];
}

/** Rows that weren't created, in the template's columns plus the reason, so they can be corrected and uploaded again. */
export function errorReportCsv(config: IdentifierConfig, rows: { row: number; values: Record<string, string>; reason: string }[]): string[][] {
  const headers = templateHeaders(config);
  return [[REPORT_ROW, ...headers, REPORT_ERRORS], ...rows.map((r) => [String(r.row), ...headers.map((h) => r.values[h] ?? ''), r.reason])];
}
